### ISSUE TITLE
没生成json文件

### ISSUE THREAD

**Issue by tesfduwen** [rickyhoho/multi_whitelist#2]
在config文件夹里没有对应的文件

**Comment by tesfduwen** [comment]
`> !!whitelist sync
Exception in thread whitelist_process:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/mcdreforged/api/decorator/new_thread.py", line 28, in wrapped_target
    raise e from None
  File "/usr/local/python3/lib/python3.7/site-packages/mcdreforged/api/decorator/new_thread.py", line 25, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins/multi_whitelist-3.0.0.mcdr/multi_whitelist/__init__.py", line 112, in sync
    sub_server_info = read_config()["servers"]
  File "plugins/multi_whitelist-3.0.0.mcdr/multi_whitelist/__init__.py", line 102, in read_config
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/multi_whitelist.json'`

**Comment by R1ckyH** [comment]
config will not be generated at the current version, so pls copy from the config file from repo
